baseURL = "/"
languageCode = "en-us"
title = "Rocky Linux"

[params]
description = "Rocky Linux is an open enterprise Operating System designed to be 100% bug-for-bug compatible with Enterprise Linux."
images = ["img/cover.png"]

[params.social]
slackurl = "https://join.slack.com/t/hpcng/shared_invite/zt-k29vv4ab-yj1ksbHK_ZkXYi6HGtTYfw"
twitter = "https://twitter.com/rocky_linux"
reddit = "https://reddit.com/r/rockylinux"
forum = "https://forums.rockylinux.org/"
email = "hello@rockylinux.org"
get_involved = "https://wiki.rockylinux.org/contributing"

[params.links]
wiki = "https://wiki.rockylinux.org/"

[params.logo]
url = "img/logo.png"
width = 127
height = 40

[params.image]
url = "img/cover.png"
width = 800
height = 600

[params.faqs]
questions = ["downstream-partner-direction", "come-in"]

DefaultContentLanguage = "en"

[languages]
  [languages.en]
    languageName = "English"
    title = "Rocky Linux"
    weight = 1
  [languages.es]
    languageName = "Español"
    title = "Rocky Linux"
    weight = 2
  [languages.nl]
    languageName = "Nederlands"
    title = "Rocky Linux"
    weight = 3
  [languages.it]
    languageName = "Italiano"
    title = "Rocky Linux"
    weight = 4
  [languages.tr]
    languageName = "Türkçe"
    title = "Rocky Linux"
    weight = 5
  [languages.de]
    languageName = "Deutsch"
    title = "Rocky Linux"
    weight = 6
  [languages.fr]
    languageName = "Français"
    title = "Rocky Linux"
    weight = 7
  [languages.lv]
    languageName = "Latviski"
    title = "Rocky Linux"
    weight = 8
  [languages.pt-pt]
    languageName = "Português"
    title = "Rocky Linux"
    weight = 9
  [languages.pt-BR]
    languageName = "Português (Brasil)"
    title = "Rocky Linux"
    weight = 10
  [languages.pl]
    languageName = "Polski"
    title = "Rocky Linux"
    weight = 11
  [languages.id]
    languageName = "Bahasa Indonesia"
    title = "Rocky Linux"
    weight = 12
  [languages.ru]
    languageName = "Русский"
    title = "Rocky Linux"
    weight = 13
  [languages.ja]
    languageName = "日本語"
    title = "Rocky Linux"
    weight = 14
  [languages.ar]
    languageName = "العربية"
    title = "روكي لينكس"
    weight = 15
  [languages.zh-cn]
    languageName = "简体中文"
    title = "Rocky Linux"
    weight = 16
  [languages.zh-hk]
    languageName = "繁體中文(香港)"
    title = "Rocky Linux"
    weight = 17
  [languages.zh-tw]
    languageName = "繁體中文(台灣)"
    title = "Rocky Linux"
    weight = 18   
  [languages.fa]
    languageName = "فارسی"
    title = "Rocky Linux"
    weight = 19
  [languages.ko]
    languageName = "한국어"
    title = "Rocky Linux"
    weight = 20
