baseURL = ""
languageCode = "en-us"
title = "Rocky Linux"

[params]
description = "Rocky Linux is an open enterprise Operating System designed to be 100% bug-for-bug compatible with Enterprise Linux."
images = ["img/cover.png"]

[params.social]
slackurl = "https://hpcng.slack.com/join/shared_invite/zt-k5z04bsh-1uqpaD1NsYVP73vzc3uKdQ"
twitter = "https://twitter.com/rocky_linux" 
reddit = "https://reddit.com/r/rockylinux"
forum = "https://forums.rockylinux.org/"
email = "hello@rockylinux.org"
get_involved = "https://wiki.rockylinux.org/contributing"

[params.links]
wiki = "https://wiki.rockylinux.org/"

[params.logo]
url = "img/logo.png"
width = 127
height = 40

[params.image]
url = "img/cover.png"
width = 800
height = 600

[params.faqs]
questions = ["downstream-partner-direction", "come-in"]

DefaultContentLanguage = "en"

[languages]
  [languages.en]
    languageName = "English"
    title = "Rocky Linux"
    weight = 2
  [languages.es]
    languageName = "Spanish"
    title = "Rocky Linux"
    weight = 1
  [languages.de]
    languageName = "Deutsch"
    title = "Rocky Linux"
    weight = 1
