baseURL = "/"
languageCode = "en-us"
title = "Rocky Linux"

[params]
description = "Rocky Linux is an open enterprise Operating System designed to be 100% bug-for-bug compatible with Enterprise Linux."
images = ["img/cover.png"]

[params.social]
slackurl = "https://hpcng.slack.com/join/shared_invite/zt-k1v012fn-SH2IG7iwhLhE0j8qb1GHVw"
twitter = "https://twitter.com/rocky_linux"
reddit = "https://reddit.com/r/rockylinux"
forum = "https://forums.rockylinux.org/"
email = "hello@rockylinux.org"
get_involved = "https://wiki.rockylinux.org/contributing"

[params.links]
wiki = "https://wiki.rockylinux.org/"

[params.logo]
url = "img/logo.png"
width = 127
height = 40

[params.image]
url = "img/cover.png"
width = 800
height = 600

[params.faqs]
questions = ["downstream-partner-direction", "come-in"]

DefaultContentLanguage = "en"

[languages]
  [languages.en]
    languageName = "English"
    title = "Rocky Linux"
    weight = 1
  [languages.es]
    languageName = "Español"
    title = "Rocky Linux"
    weight = 2
  [languages.nl]
    languageName = "Nederlands"
    title = "Rocky Linux"
    weight = 3
  [languages.it]
    languageName = "Italiano"
    title = "Rocky Linux"
    weight = 4
  [languages.tr]
    languageName = "Türkçe"
    title = "Rocky Linux"
    weight = 5
  [languages.de]
    languageName = "Deutsch"
    title = "Rocky Linux"
    weight = 6
  [languages.ru]
    languageName = "Русский"
    title = "Rocky Linux"
    weight = 7
  [languages.lv]
    languageName = "Latviski"
    title = "Rocky Linux"
    weight = 8
  [languages.zh]
    languageName = "简体中文"
    weight = 9
  [languages.pt-BR]
    languageName = "Português (Brasil)"
    title = "Rocky Linux"
    weight = 10
  [languages.ja]
    languageName = "日本語"
    title = "Rocky Linux"
    weight = 11
  [languages.pt-pt]
    languageName = "Português"
    title = "Rocky Linux"
    weight = 12
